# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16E9TNx2jR7OD8Neirt1nMnmfU2PCxHkK
"""

import pandas as pd
import numpy as np
import re

from sklearn.model_selection import train_test_split, StratifiedKFold, StratifiedShuffleSplit
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    roc_auc_score, average_precision_score, brier_score_loss,
    precision_recall_curve, roc_curve, confusion_matrix, classification_report
)

import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

# Mount Google Drive to access files
from google.colab import drive
drive.mount('/content/drive')

# Helper functions for robust metric calculation and data split summary
def summarize_split(y_true, name):
    """
    Prints summary statistics for a given split (y_true).
    """
    total_samples = len(y_true)
    positive_samples = y_true.sum()
    negative_samples = total_samples - positive_samples

    if total_samples > 0:
        percent_positive = (positive_samples / total_samples) * 100
        percent_negative = (negative_samples / total_samples) * 100
    else:
        percent_positive = 0.0
        percent_negative = 0.0

    print(f"--- {name} Split Summary ---")
    print(f"Total Samples: {total_samples}")
    print(f"Positive Samples (y=1): {positive_samples} ({percent_positive:.2f}%) ")
    print(f"Negative Samples (y=0): {negative_samples} ({percent_negative:.2f}%) ")
    print("-------------------------")

def safe_pr_auc(y_true, y_proba):
    """
    Calculates PR-AUC robustly, returning 0.0 if no positive samples.
    """
    if y_true.sum() > 0:
        return average_precision_score(y_true, y_proba)
    else:
        return 0.0

def safe_roc_auc(y_true, y_proba):
    """
    Calculates ROC-AUC robustly, returning 0.0 if only one class is present.
    """
    if len(np.unique(y_true)) < 2:
        return 0.0
    else:
        return roc_auc_score(y_true, y_proba)

# Evaluation helpers (updated to use safe_roc_auc and safe_pr_auc)
def evaluate(model, X, y, name='VAL'):
    proba = model.predict_proba(X)[:,1]
    pred   = (proba >= 0.5).astype(int)

    auc   = safe_roc_auc(y, proba)
    ap    = safe_pr_auc(y, proba)
    brier = brier_score_loss(y, proba)
    cm    = confusion_matrix(y, pred)
    print(f'[{name}] AUROC={auc:.3f} | PR-AUC={ap:.3f} | Brier={brier:.3f}')
    print(f'[{name}] Confusion Matrix:\n{cm}')
    print(f'[{name}] Classification Report:\n{classification_report(y, pred, digits=3)}')
    return {'auroc':auc, 'pr_auc':ap, 'brier':brier, 'cm':cm}

def evaluate_proba(y_true, y_proba, name='HEURISTIC'):
    pred   = (y_proba >= 0.5).astype(int)

    auc = safe_roc_auc(y_true, y_proba)
    ap = safe_pr_auc(y_true, y_proba)
    brier = brier_score_loss(y_true, y_proba)
    cm    = confusion_matrix(y_true, pred)
    print(f'[{name}] AUROC={auc:.3f} | PR-AUC={ap:.3f} | Brier={brier:.3f}')
    print(f'[{name}] Confusion Matrix:\n{cm}')
    print(f'[{name}] Classification Report:\n{classification_report(y_true, pred, digits=3)}')
    return {'auroc':auc, 'pr_auc':ap, 'brier':brier, 'cm':cm}

# ==== 1) Load your two source tables (update paths if needed) ====
incidents = pd.read_csv('/content/drive/MyDrive/INST414/incidents.csv', encoding='latin-1')
entries   = pd.read_csv('/content/drive/MyDrive/INST414/fulldata.csv', encoding='utf-16', sep='\t')
metro_stations = pd.read_csv('/content/drive/MyDrive/INST414/metro.csv',encoding='latin-1')

# ==== 2) Initial Cleaning and Date Parsing ====
# Convert time columns in incidents to datetime
for col in ['start_time', 'estimated_rts']:
    if col in incidents.columns:
        incidents[col] = pd.to_datetime(incidents[col], errors='coerce')

# Keep elevators/escalators only
incidents = incidents[incidents['unit_type'].isin(['ELEVATOR','ESCALATOR'])].copy()

# Extract date from incident start_time
incidents['date'] = incidents['start_time'].dt.date

# Convert 'Date' column in entries to datetime
entries['Date'] = pd.to_datetime(entries['Date'], errors='coerce')
entries['date'] = entries['Date'].dt.date

# Rename 'Entries' to 'entries' for consistency
entries = entries.rename(columns={'Entries':'entries'})

# Aggregate entries by Station Name and date to sum entries
aggregated_entries = entries.groupby(['Station Name', 'date'])['entries'].sum().reset_index()

# Define station name cleaning function
def clean_station_name(name):
    name = str(name)
    if ',' in name:
        name = name.split(',')[0].strip()
    name = name.replace('Metro Station', '').strip()
    name = name.replace('Station', '').strip()
    name = name.replace('North', '').strip()
    name = name.replace('South', '').strip()
    name = name.replace('East', '').strip()
    name = name.replace('West', '').strip()
    name = name.replace(' & ', '-').replace(' ', '-').strip('-')
    return name

# Apply cleaning function to incidents' station names and aggregated_entries' station names
incidents['cleaned_station_name'] = incidents['station_name'].apply(clean_station_name)
aggregated_entries['cleaned_station_name'] = aggregated_entries['Station Name'].apply(clean_station_name)

# Apply cleaning function to metro_stations' station names
metro_stations['cleaned_station_name'] = metro_stations['NAME'].apply(clean_station_name)

# ==== 3) Generate `df` and `data` tables ====

# Extract min and max dates from incidents and entries for overall date range
min_date_overall = min(incidents['date'].min(), entries['date'].min())
max_date_overall = max(incidents['date'].max(), entries['date'].max())
full_date_range = pd.date_range(start=min_date_overall, end=max_date_overall)

unique_stations = metro_stations['cleaned_station_name'].unique()
station_date_grid = pd.MultiIndex.from_product([unique_stations, full_date_range], names=['cleaned_station_name', 'date']).to_frame(index=False)

# Ensure 'date' column in aggregated_entries is datetime64[ns] before merging
aggregated_entries['date'] = pd.to_datetime(aggregated_entries['date'])

# Merge aggregated_entries with the station_date_grid
df = pd.merge(station_date_grid, aggregated_entries, on=['cleaned_station_name', 'date'], how='left')
df['entries'] = df['entries'].fillna(0) # Fill NaN entries with 0

# Regenerate daily_flag using cleaned station names for accurate merging
daily_flag = (incidents.groupby(['cleaned_station_name','date'])
                        .size()
                        .reset_index(name='outage_cnt'))
daily_flag['outage_any'] = (daily_flag['outage_cnt'] > 0).astype(int)

# Convert daily_flag's date column to datetime64[ns] for consistent merge
daily_flag['date'] = pd.to_datetime(daily_flag['date'])

# Merge daily_flag with the df DataFrame
df = pd.merge(df, daily_flag, on=['cleaned_station_name', 'date'], how='left')

# Fill NaNs for outage-related columns with 0
df['outage_cnt'] = df['outage_cnt'].fillna(0)
df['outage_any'] = df['outage_any'].fillna(0).astype(int)

# Drop the original 'Station Name' column from df if it exists (from aggregated_entries merge)
if 'Station Name' in df.columns:
    df = df.drop(columns=['Station Name'])

# Rename 'cleaned_station_name' to 'station_code'
df = df.rename(columns={'cleaned_station_name': 'station_code'})

# Calculate rolling 14-day outage rate per station
tmp = df.sort_values(['station_code','date']).copy()
tmp['outage_roll14'] = (tmp.groupby('station_code')['outage_any']
                          .transform(lambda s: s.shift(1).rolling(14, min_periods=1).mean()))
tmp['outage_roll14'] = tmp['outage_roll14'].fillna(0.0)

# Duplicate rows to create two “shifts” per day
long = []
for sh in ['AM_peak','PM_peak']:
    t = tmp.copy()
    t['shift'] = sh
    long.append(t)
data = pd.concat(long, ignore_index=True)

# Generate target variable: next-window outage
data = data.sort_values(['station_code','date','shift'])
data['y_next'] = (data.groupby(['station_code','shift'])['outage_any']
                    .shift(-1))
data = data.dropna(subset=['y_next']).copy()
data['y_next'] = data['y_next'].astype(int)

# Convert 'date' to datetime for calendar features
data['date'] = pd.to_datetime(data['date'])
# Add calendar features
data['dow']   = data['date'].dt.weekday
data['month'] = data['date'].dt.month

print("DataFrame `df` and `data` generated and updated successfully.")

# ==== 4) Feature Engineering: Service Change Data Parsing and Integration ====
unstructured_text = """Service Change 1: Station Red Line (Farragut North) from 2025-01-01 to 2025-01-15. Description: Escalator maintenance.
Service Change 2: Station Blue Line (Metro Center) from 2025-02-01 to 2025-02-28. Description: Track work near platforms.
Construction Event: Green Line (Columbia Heights) starting 2025-03-10, ending 2025-04-20. Description: Platform extension project. Additional notes: Expect delays.
Service Change 3: Station Orange Line (Rosslyn) from 2025-05-01 to 2025-05-30. Description: Weekend closures for signal upgrades."""

extracted_data = []
# Corrected Regex pattern to capture: Station Name, Start Date, End Date, and Description
pattern = re.compile(
    r"(?:Service Change \d+: Station \S+ Line \((?P<station_name>[^)]+)\) from (?P<start_date>\d{4}-\d{2}-\d{2}) to (?P<end_date>\d{4}-\d{2}-\d{2})\. Description: (?P<description>.+))"
    r"|(?:Construction Event: \S+ Line \((?P<station_name_alt>[^)]+)\) starting (?P<start_date_alt>\d{4}-\d{2}-\d{2}), ending (?P<end_date_alt>\d{4}-\d{2}-\d{2})\. Description: (?P<description_alt>.+))"
)

for line in unstructured_text.strip().split('\n'):
    match = pattern.match(line)
    if match:
        if match.group('station_name'):
            station_name = match.group('station_name')
            start_date = match.group('start_date')
            end_date = match.group('end_date')
            description = match.group('description')
        else: # Must be the 'alt' groups for Construction Event
            station_name = match.group('station_name_alt')
            start_date = match.group('start_date_alt')
            end_date = match.group('end_date_alt')
            description = match.group('description_alt')

        extracted_data.append({
            'Station Name': station_name,
            'Start Date': start_date,
            'End Date': end_date,
            'Description': description.strip()
        })

service_changes_df = pd.DataFrame(extracted_data)
service_changes_df['Start Date'] = pd.to_datetime(service_changes_df['Start Date'])
service_changes_df['End Date'] = pd.to_datetime(service_changes_df['End Date'])
service_changes_df['duration_days'] = (service_changes_df['End Date'] - service_changes_df['Start Date']).dt.days + 1
service_changes_df['cleaned_station_name'] = service_changes_df['Station Name'].apply(clean_station_name)

active_events = []
for index, row in service_changes_df.iterrows():
    station = row['cleaned_station_name']
    start = row['Start Date']
    end = row['End Date']
    for current_date in pd.date_range(start=start, end=end):
        active_events.append({'cleaned_station_name': station, 'date': current_date.date(), 'event_id': index})

active_events_df = pd.DataFrame(active_events)
active_events_df['date'] = pd.to_datetime(active_events_df['date'])

active_events_aggregated_df = (
    active_events_df.groupby(['cleaned_station_name', 'date'])
    .size()
    .reset_index(name='simultaneous_changes_count')
)
active_events_aggregated_df['active_event_flag'] = (active_events_aggregated_df['simultaneous_changes_count'] > 0).astype(int)
active_events_aggregated_df = active_events_aggregated_df.rename(columns={'cleaned_station_name': 'station_code'})

# Merge service change features into main data DataFrame
data = pd.merge(data, active_events_aggregated_df, on=['station_code', 'date'], how='left')
data['simultaneous_changes_count'] = data['simultaneous_changes_count'].fillna(0).astype(int)
data['active_event_flag'] = data['active_event_flag'].fillna(0).astype(int)

print("Feature engineering for service change data completed and integrated.")

# Define cat_cols and num_cols after feature engineering
cat_cols = ['station_code','shift','dow','month']
num_cols = ['entries','outage_roll14', 'simultaneous_changes_count', 'active_event_flag']

# Define X_full and y_full for stratified splitting
X_full = data[cat_cols + num_cols]
y_full = data['y_next']

# Implement stratified data splitting
print(f"Total positive samples in y_full: {y_full.sum()}")

# Separate positive and negative samples
X_pos = X_full[y_full == 1]
y_pos = y_full[y_full == 1]
X_neg = X_full[y_full == 0]
y_neg = y_full[y_full == 0]

# Initialize empty dataframes for the splits
X_train, y_train = pd.DataFrame(), pd.Series(dtype=int)
X_val, y_val = pd.DataFrame(), pd.Series(dtype=int)
X_test, y_test = pd.DataFrame(), pd.Series(dtype=int)

# Distribute positive samples
if len(y_pos) > 0:
    if len(y_pos) == 1:
        X_train = pd.concat([X_train, X_pos.iloc[[0]]])
        y_train = pd.concat([y_train, y_pos.iloc[[0]]])
    elif len(y_pos) == 2:
        X_train = pd.concat([X_train, X_pos.iloc[[0]]])
        y_train = pd.concat([y_train, y_pos.iloc[[0]]])
        X_val = pd.concat([X_val, X_pos.iloc[[1]]])
        y_val = pd.concat([y_val, y_pos.iloc[[1]]])
    else:
        split_pos_initial = StratifiedShuffleSplit(n_splits=1, test_size=0.1, random_state=42)
        for train_val_pos_idx, test_pos_idx in split_pos_initial.split(X_pos, y_pos):
            X_train_val_pos, X_test_pos = X_pos.iloc[train_val_pos_idx], X_pos.iloc[test_pos_idx]
            y_train_val_pos, y_test_pos = y_pos.iloc[train_val_pos_idx], y_pos.iloc[test_pos_idx]

        split_pos_train_val = StratifiedShuffleSplit(n_splits=1, test_size=0.2/0.9, random_state=42)
        for train_pos_idx, val_pos_idx in split_pos_train_val.split(X_train_val_pos, y_train_val_pos):
            X_train_pos, X_val_pos = X_train_val_pos.iloc[train_pos_idx], X_train_val_pos.iloc[val_pos_idx]
            y_train_pos, y_val_pos = y_train_val_pos.iloc[train_pos_idx], y_train_val_pos.iloc[val_pos_idx]

        X_train = pd.concat([X_train, X_train_pos])
        y_train = pd.concat([y_train, y_train_pos])
        X_val = pd.concat([X_val, X_val_pos])
        y_val = pd.concat([y_val, y_val_pos])
        X_test = pd.concat([X_test, X_test_pos])
        y_test = pd.concat([y_test, y_test_pos])

# Split negative samples using StratifiedShuffleSplit
split_neg_initial = StratifiedShuffleSplit(n_splits=1, test_size=0.1, random_state=42)
for train_val_neg_idx, test_neg_idx in split_neg_initial.split(X_neg, y_neg):
    X_train_val_neg, X_test_neg = X_neg.iloc[train_val_neg_idx], X_neg.iloc[test_neg_idx]
    y_train_val_neg, y_test_neg = y_neg.iloc[train_val_neg_idx], y_neg.iloc[test_neg_idx]

split_neg_train_val = StratifiedShuffleSplit(n_splits=1, test_size=0.2/0.9, random_state=42)
for train_neg_idx, val_neg_idx in split_neg_train_val.split(X_train_val_neg, y_train_val_neg):
    X_train_neg, X_val_neg = X_train_val_neg.iloc[train_neg_idx], X_train_val_neg.iloc[val_neg_idx]
    y_train_neg, y_val_neg = y_train_val_neg.iloc[train_neg_idx], y_train_val_neg.iloc[val_neg_idx]

# Concatenate negative samples with the positive samples that were already distributed
X_train = pd.concat([X_train, X_train_neg])
y_train = pd.concat([y_train, y_train_neg])
X_val = pd.concat([X_val, X_val_neg])
y_val = pd.concat([y_val, y_val_neg])
X_test = pd.concat([X_test, X_test_neg])
y_test = pd.concat([y_test, y_test_neg])

# Ensure index is reset to avoid issues with iloc later
X_train = X_train.reset_index(drop=True)
y_train = y_train.reset_index(drop=True)
X_val = X_val.reset_index(drop=True)
y_val = y_val.reset_index(drop=True)
X_test = X_test.reset_index(drop=True)
y_test = y_test.reset_index(drop=True)

print("Stratified data splitting complete with explicit handling of positive samples.")
print(f"X_train shape: {X_train.shape}, y_train shape: {y_train.shape}, Positive in Train: {y_train.sum()}")
print(f"X_val shape: {X_val.shape}, y_val shape: {y_val.shape}, Positive in Val: {y_val.sum()}")
print(f"X_test shape: {X_test.shape}, y_test shape: {y_test.shape}, Positive in Test: {y_test.sum()}")

# Print summary of splits to confirm positive sample distribution
summarize_split(y_train, 'Train')
summarize_split(y_val, 'Validation')
summarize_split(y_test, 'Test')

# ==== 6) Logistic Regression Pipeline Setup ====
preprocess = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), cat_cols),
        ('num', StandardScaler(), num_cols)
    ],
    remainder='drop'
)

logreg = LogisticRegression(
    penalty='l2', C=1.0, max_iter=200, solver='lbfgs', class_weight=None
)

logreg_balanced = LogisticRegression(
    penalty='l2', C=1.0, max_iter=200, solver='lbfgs', class_weight='balanced'
)

pipe = Pipeline(steps=[('prep', preprocess),
                      ('clf', logreg)])

pipe_balanced = Pipeline(steps=[('prep', preprocess),
                               ('clf', logreg_balanced)])

print("Logistic Regression pipelines set up.")

# ==== 7) Model Training and Evaluation ====

# Train and evaluate Original Logistic Regression
print("\n--- Original Logistic Regression Evaluation ---")
pipe.fit(X_train, y_train)
metrics_val  = evaluate(pipe, X_val,  y_val,  'VAL')
metrics_test = evaluate(pipe, X_test, y_test, 'TEST')

# Evaluate Heuristic Baseline
print("\n--- Heuristic Baseline Evaluation ---")
proba_heuristic_val = X_val['outage_roll14']
proba_heuristic_test = X_test['outage_roll14']
metrics_heuristic_val = evaluate_proba(y_val, proba_heuristic_val, name='Heuristic_VAL')
metrics_heuristic_test = evaluate_proba(y_test, proba_heuristic_test, name='Heuristic_TEST')

# Train and evaluate Logistic Regression with Balanced Class Weight
print("\n--- Balanced Class Weight Logistic Regression Evaluation ---")
pipe_balanced.fit(X_train, y_train)
metrics_val_balanced  = evaluate(pipe_balanced, X_val,  y_val,  'VAL_BALANCED')
metrics_test_balanced = evaluate(pipe_balanced, X_test, y_test, 'TEST_BALANCED')

print("Models trained and evaluated.")

# ==== 8) Visualizations ====
# ROC and PR curves for Balanced Logistic Regression (using Validation set)
proba_val_balanced = pipe_balanced.predict_proba(X_val)[:,1]
fpr_val_balanced, tpr_val_balanced, _ = roc_curve(y_val, proba_val_balanced)
prec_val_balanced, recall_val_balanced, _ = precision_recall_curve(y_val, proba_val_balanced)

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(fpr_val_balanced, tpr_val_balanced)
plt.plot([0,1],[0,1],'--')
plt.title('ROC (Validation Set) - Balanced Logistic Regression')
plt.xlabel('FPR'); plt.ylabel('TPR')

plt.subplot(1, 2, 2)
plt.plot(recall_val_balanced, prec_val_balanced)
plt.title('Precision–Recall (Validation Set) - Balanced Logistic Regression')
plt.xlabel('Recall'); plt.ylabel('Precision')

plt.tight_layout()
plt.show()

# Top coefficients for the balanced model
ohe_balanced = pipe_balanced.named_steps['prep'].named_transformers_['cat']
cat_feature_names_balanced = ohe_balanced.get_feature_names_out(cat_cols)
feat_names_balanced = np.r_[cat_feature_names_balanced, np.array(num_cols)]
coef_balanced = pipe_balanced.named_steps['clf'].coef_.ravel()
top_idx_balanced = np.argsort(np.abs(coef_balanced))[::-1][:15]

plt.figure(figsize=(8,6))
sns.barplot(x=np.abs(coef_balanced[top_idx_balanced]), y=feat_names_balanced[top_idx_balanced], orient='h')
plt.title('Top |coef| Features — Balanced Logistic Regression')
plt.xlabel('|Coefficient|'); plt.ylabel('Feature'); plt.tight_layout()
plt.show()

# Conditional plotting for Test Set ROC and PR curves
print("\n--- Visualizations for Test Set ---")
proba_test_balanced = pipe_balanced.predict_proba(X_test)[:,1]

if np.sum(y_test) > 0:
    fpr_test_balanced, tpr_test_balanced, _ = roc_curve(y_test, proba_test_balanced)
    prec_test_balanced, recall_test_balanced, _ = precision_recall_curve(y_test, proba_test_balanced)

    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.plot(fpr_test_balanced, tpr_test_balanced)
    plt.plot([0,1],[0,1],'--')
    plt.title('ROC (Test Set) - Balanced Logistic Regression')
    plt.xlabel('FPR'); plt.ylabel('TPR')

    plt.subplot(1, 2, 2)
    plt.plot(recall_test_balanced, prec_test_balanced)
    plt.title('Precision–Recall (Test Set) - Balanced Logistic Regression')
    plt.xlabel('Recall'); plt.ylabel('Precision')

    plt.tight_layout()
    plt.show()
else:
    print("ROC and PR curves for the test set cannot be plotted due to a lack of positive samples.")

# ==== 9) Comparison Table ====
results = []

# Original Logistic Regression
results.append({'Model': 'Logistic Regression', 'Set': 'VAL', 'AUROC': metrics_val['auroc'], 'PR-AUC': metrics_val['pr_auc'], 'Brier': metrics_val['brier']})
results.append({'Model': 'Logistic Regression', 'Set': 'TEST', 'AUROC': metrics_test['auroc'], 'PR-AUC': metrics_test['pr_auc'], 'Brier': metrics_test['brier']})

# Heuristic Baseline
results.append({'Model': 'Heuristic Baseline', 'Set': 'VAL', 'AUROC': metrics_heuristic_val['auroc'], 'PR-AUC': metrics_heuristic_val['pr_auc'], 'Brier': metrics_heuristic_val['brier']})
results.append({'Model': 'Heuristic Baseline', 'Set': 'TEST', 'AUROC': metrics_heuristic_test['auroc'], 'PR-AUC': metrics_heuristic_test['pr_auc'], 'Brier': metrics_heuristic_test['brier']})

# Logistic Regression with balanced class weights
results.append({'Model': 'Logistic Regression (Balanced)', 'Set': 'VAL', 'AUROC': metrics_val_balanced['auroc'], 'PR-AUC': metrics_val_balanced['pr_auc'], 'Brier': metrics_val_balanced['brier']})
results.append({'Model': 'Logistic Regression (Balanced)', 'Set': 'TEST', 'AUROC': metrics_test_balanced['auroc'], 'PR-AUC': metrics_test_balanced['pr_auc'], 'Brier': metrics_test_balanced['brier']})

comparison_table = pd.DataFrame(results)
print("\n--- Model Performance Comparison ---")
print(comparison_table.to_markdown(index=False))

# Implement stratified k-fold cross-validation
print("\n--- Starting Stratified K-Fold Cross-Validation ---")

# Define StratifiedKFold splitter
n_splits_cv = 5 # Number of folds for cross-validation
skf = StratifiedKFold(n_splits=n_splits_cv, shuffle=True, random_state=42)

all_metrics_original_cv = []
all_metrics_balanced_cv = []

fold_num = 1
for train_index, test_index in skf.split(X_full, y_full):
    X_train_cv, X_test_cv = X_full.iloc[train_index], X_full.iloc[test_index]
    y_train_cv, y_test_cv = y_full.iloc[train_index], y_full.iloc[test_index]

    print(f"\n--- Cross-Validation Fold {fold_num}/{n_splits_cv} ---")
    summarize_split(y_train_cv, f'CV Fold {fold_num} Train')
    summarize_split(y_test_cv, f'CV Fold {fold_num} Test')

    # Original Logistic Regression CV
    print(f"Training Original LR for Fold {fold_num}...")
    pipe.fit(X_train_cv, y_train_cv)
    fold_metrics_original = evaluate(pipe, X_test_cv, y_test_cv, f'CV_ORIGINAL_FOLD{fold_num}')
    all_metrics_original_cv.append(fold_metrics_original)

    # Balanced Logistic Regression CV
    print(f"Training Balanced LR for Fold {fold_num}...")
    pipe_balanced.fit(X_train_cv, y_train_cv)
    fold_metrics_balanced = evaluate(pipe_balanced, X_test_cv, y_test_cv, f'CV_BALANCED_FOLD{fold_num}')
    all_metrics_balanced_cv.append(fold_metrics_balanced)

    fold_num += 1

print("\n--- Stratified K-Fold Cross-Validation Complete ---")

# Cross-Validation Results Summary
print("\n--- Cross-Validation Results Summary ---")

# Extract metrics for Original Logistic Regression
original_auroc = [m['auroc'] for m in all_metrics_original_cv]
original_pr_auc = [m['pr_auc'] for m in all_metrics_original_cv]
original_brier = [m['brier'] for m in all_metrics_original_cv]

# Calculate mean and std for Original Logistic Regression
mean_original_auroc = np.mean(original_auroc)
std_original_auroc = np.std(original_auroc)
mean_original_pr_auc = np.mean(original_pr_auc)
std_original_pr_auc = np.std(original_pr_auc)
mean_original_brier = np.mean(original_brier)
std_original_brier = np.std(original_brier)

print("\nOriginal Logistic Regression (Cross-Validation Mean \u00b1 Std):")
print(f"  AUROC: {mean_original_auroc:.3f} \u00b1 {std_original_auroc:.3f}")
print(f"  PR-AUC: {mean_original_pr_auc:.3f} \u00b1 {std_original_pr_auc:.3f}")
print(f"  Brier: {mean_original_brier:.3f} \u00b1 {std_original_brier:.3f}")

# Extract metrics for Balanced Logistic Regression
balanced_auroc = [m['auroc'] for m in all_metrics_balanced_cv]
balanced_pr_auc = [m['pr_auc'] for m in all_metrics_balanced_cv]
balanced_brier = [m['brier'] for m in all_metrics_balanced_cv]

# Calculate mean and std for Balanced Logistic Regression
mean_balanced_auroc = np.mean(balanced_auroc)
std_balanced_auroc = np.std(balanced_auroc)
mean_balanced_pr_auc = np.mean(balanced_pr_auc)
std_balanced_pr_auc = np.std(balanced_pr_auc)
mean_balanced_brier = np.mean(balanced_brier)
std_balanced_brier = np.std(balanced_brier)

print("\nBalanced Logistic Regression (Cross-Validation Mean \u00b1 Std):")
print(f"  AUROC: {mean_balanced_auroc:.3f} \u00b1 {std_balanced_auroc:.3f}")
print(f"  PR-AUC: {mean_balanced_pr_auc:.3f} \u00b1 {std_balanced_pr_auc:.3f}")
print(f"  Brier: {mean_balanced_brier:.3f} \u00b1 {std_balanced_brier:.3f}")

print("The model training and evaluation pipeline, including stratified k-fold cross-validation, has been successfully re-executed. All dataframes and metrics are updated.")

"""## Summary:

### Q&A
The `NameError` related to undefined cross-validation metrics was resolved by implementing a 5-fold stratified k-fold cross-validation for both the original and balanced Logistic Regression models. This process ensured that the `all_metrics_original_cv` and `all_metrics_balanced_cv` lists were properly populated with evaluation metrics for each fold before being used in subsequent analyses.

### Data Analysis Key Findings
*   **Data Integration and Feature Engineering:** The data generation process was successfully updated to include all metro stations, clean station names, and create a comprehensive date-station grid. This resulted in a final `data` DataFrame incorporating rolling 14-day outage rates, `AM_peak`/`PM_peak` shifts, the `y_next` target variable, and calendar features.
*   **Extreme Class Imbalance:** The dataset exhibits extreme class imbalance, with positive samples constituting approximately 0.1% of the total. This severely impacts model evaluation and stability, as evidenced by `UserWarning` during cross-validation about sparsely populated classes in folds.
*   **Original Logistic Regression Performance (Holdout Sets):**
    *   Achieved high AUROC values (0.97-0.98) but very low PR-AUC (0.05-0.11) on validation and test sets.
    *   Brier scores were low (0.001-0.002), indicating good calibration for the majority class but a complete failure to identify the minority class (zero true positives).
*   **Original Logistic Regression Performance (Cross-Validation):** Mean AUROC was 0.857 $\pm$ 0.098, mean PR-AUC was 0.054, and mean Brier score was 0.001. The high standard deviation for AUROC reflects significant variability across folds due to data imbalance.
*   **Balanced Logistic Regression Performance (Holdout Sets):**
    *   Achieved high AUROC (0.98-0.99) and a slightly better PR-AUC (0.04-0.07) compared to the original model.
    *   Recall for the positive class improved dramatically to 1.0, meaning all positive samples were identified. However, this came at the cost of significantly lower precision (e.g., 0.022 for validation, 0.027 for test) and higher Brier scores (0.037-0.040), indicating worse calibration.
*   **Balanced Logistic Regression Performance (Cross-Validation):** Mean AUROC was 0.855 $\pm$ 0.096, mean PR-AUC was 0.037, and mean Brier score was 0.031. Similar to the holdout sets, balancing improved recall but lowered precision and increased miscalibration as reflected in the higher Brier score.
*   **Heuristic Baseline Performance:** Consistently showed poor performance with AUROC around 0.5-0.55 and very low PR-AUC (0.001-0.003), performing barely better than random chance.

### Insights or Next Steps
*   **Address Extreme Imbalance More Robustly:** Given the persistent low PR-AUC scores and the instability of cross-validation due to extreme class imbalance, explore advanced techniques like oversampling (SMOTE), undersampling, or ensemble methods specifically designed for highly imbalanced datasets.
*   **Focus on Feature Engineering and External Data:** The current features may not be sufficiently discriminative for predicting rare events. Further feature engineering, potentially incorporating external data sources or more complex temporal features, could improve model performance for the minority class.

"""